### ISSUE TITLE
Add united kingdom?

### ISSUE THREAD

**Issue by johnsie** [cipriancraciun/covid19-datasets#1]
Thanks for the very informative graphs. Is it possible to get the UK added to the graphs? 

Thanks

**Comment by cipriancraciun** [comment]
I can add it, however I'm not sure in which category should I add it.

To be more clear, at the moment (besides the per continents and per sub-continents graphs) I have two "groups" of countries:
* the major ones (Italy, Spain, China, etc.) which are way over 10k cases;
* "Romania" group which compares my own country with a few others (including UK);

I could add a few more groups, say those between 5K and 15K cases (which should include a few European countries, including UK).

@johnsie Could you propose a few groups?  (Perhaps ones that interest you most?)

(I'll try to provide the graphs later today or tomorrow morning;  now I'm trying to update the scripts once more due to JHU changing the datasets.)

**Comment by cipriancraciun** [comment]
@johnsie OK, I've added UK and a few other countries, in the following groups:

* `global` contains the "problematic" countries (>15K) + China + Korea + US;
* `europe-major` contains (at the moment) mostly the same "problematic" countries + China;
* `europe-minor` contains those countries that are above 2K and bellow 15K, thus including UK, plus the "problematic" countries (but limited to first 25 days to aid comparisons;)
* `romania` -- mostly eastern europe (limited to 15 days);

(Again, the limitation of number of days is only to aid the interpretation of the graphs, and includes the targeted countries and a few extra days as well.  They only limit the "height" of the graph for the "problematic" countries.)

See the `./plots` folder.
