### ISSUE TITLE
NY Times counties data stupped updating on Jan 17

### ISSUE THREAD

**Issue by jgoerzen** [cipriancraciun/covid19-datasets#45]
Hi,

The upstream NY Times data is still updating, but the NY Times county data in here looks to have stopped updating on Jan. 17.

Thanks!

**Comment by cipriancraciun** [comment]
Indeed I've been slacking on the updating the datasets.

Out of curiosity, I know you've used my dataset in the past, but because I've failed to update daily the datasets at county level, and because you've said nothing in the last few weeks, I assumed you've moved on to another dataset.  So my question is if you are relying on this dataset?

----

Setting that asside, I could commit on a schedule like the following:
* updates of country-level and state-level (for US) once a week;  (say on monday to capture the data until the end of the previous week;)
* updates for US level once a month;

Would that schedule work for you?

Would you have another schedule in mind?

----

As stated previously the main issue with re-generating everything each day is the amount of CPU time that my `jq` scripts require.  (I know, it's suboptimal, they could have been rewriten in something else, but at the moment I don't have the time for that.)

**Comment by jgoerzen** [comment]
Hi,

That would indeed be helpful.  I am currently pulling your dataset into covid19db and plan to continue doing so.  I have also written my own importer for the NY Times county-level data, as having that daily was important.  But you still have several datasets I don't, and are presenting them in a unified schema, which I'm not, so you work is also important.

Totally understood the limits you've got there.

Thanks!

**Comment by cipriancraciun** [comment]
OK, then I'll try to stick to the proposed schedule.

I'll build the weekly datasets on monday or tuesday, and the monthly datasets around the 15th.

**Comment by cipriancraciun** [comment]
Since I've hit the problem described in #46, I'm closing this issue (see that issue for details).
