### ISSUE TITLE
Introduce (approximate) *cohorte-views* for deaths-rates?

### ISSUE THREAD

**Issue by gottfriedhelms** [cipriancraciun/covid19-datasets#8]
Dear Ciprian - I was thinking about the change-of-deathrates (deaths/confirmed) in a couple of inspected countries.      

Taking your rich timeseries dataset (**applause for it**) I tried various parameters for the *mean individual test-to-death lifespan*.      

Thus in an excel-file I computed the ratios from the accumulated files `[deaths]_{d+lag} / [confirmed]_d` where `d` is the day-index and `lag` the estimated lifespan from the event of being tested to the event of deaths First, for Germany I got a stabilizing ratio of ca 6% when the `lag` was about 12 days, and for Italy of ca 24% when the `lag` was about 5 days.                         

These are **crude** guesses from inspection of the curves when the `lag` parameter was changed and the most horicontal / constant form of the curve was selected as *most appropriate*.       

![Cohorte_Germany](https://user-images.githubusercontent.com/33901438/77863708-7a08af00-7224-11ea-93a0-f3d43f08e88b.png)                           

![Cohorte_italy](https://user-images.githubusercontent.com/33901438/77863921-344ce600-7226-11ea-88c0-589774dc1999.png)

It is a bit laborous to reconfigure this in excel for various more countries and changeable parameters plus making visually parallel curves having neighboured parameters for `lag` by hand. So after this little peek-into-data I've paused so far.                         

In short: the idea behind is, to define such *best lag parameter* and from this estimate the country-specific deathrate-in-cohortes where the cohortes are estimated via the `lag`, meaning the (average) lifespan after (country-specific governmentally granted) testing-for-corona-positivity.                     
This felt to be a very good idea in principle, and lacks the true cohort-determination. But possibly extendable with new ideas and data.                        

I tried to improve the meaningfulness of such estimates by using the `daily-change` versions of the data instead of the accumulated data, and moreover by using the `infected` instead of the `confirmed` values for the lagged day-indexes. While the occuring tendencies seem to suggest the same best `lag` parameter, the curves are more oscillating, and thus possibly more irritating the reader. Again: maybe here could some more insight be helpful by checking more countries and see whether this gives indeed some approximately consistent rules for a general approach ...

**Comment by cipriancraciun** [comment]
@gottfriedhelms thanks for the very detailed description;  the survival rate is indeed a metric I was wondering about.

Although I'm not a statistician (heck, I barely passed my math related subjects in university) :), I understood your reasoning, and it makes sense.

However my assumption is that the death rate should stabilize as the numbers get higher and higher (because it evens out the initial lag).  For example:
* in, https://github.com/cipriancraciun/covid19-datasets/blob/master/plots/jhu/europe-major/svg/relative-deaths.svg
* the death-rate for Germany is somewhere around 1%;
* for China around 4%;
* and in Italy it keeps rising;

Now, by using your lag estimate the value for Germany is 6%, which is way higher than 1% from my graph (which just divides the deaths and confirmed in the same day), and granted I understand this is wrong because it takes a few days for the illness to make its effects.

Could you try this estimate for China and South Korea, which has the most datapoints?

In the interim I will think about how to compute this analysis for other countries.

**Comment by cipriancraciun** [comment]
@gottfriedhelms Please make sure you check the `day_index_0` (although I suggest starting with `day_index_1k`) that the values are consecutive, or if not, adjust the chosen "lag" date accordingly.

(Unfortunately there are dates missing from the dataset due to lack of reporting, and I decided to drop any rows that don't have any actual change.  See issue #9.)

**Comment by gottfriedhelms** [comment]
Am 31.03.2020 um 21:34 schrieb Ciprian Dorin Craciun:
> @gottfriedhelms <https://github.com/gottfriedhelms> Please make sure you check the |day_index_0| 
> (although I suggest starting with |day_index_1k|) that the values are consecutive,
> or if not, adjust the chosen "lag" date accordingly.

Thanks for notification - I've seen this and introduced rows
for the missing days with rough interpolated values for confirmed,deaths,recovered and infected.
(This is part of the term "laborious" in my earlier msg ;-) )

CU -
Gottfried
---------------------------

**Comment by gottfriedhelms** [comment]
As on your request , I fiddled the graphs for Japan and South Korea from your data (up to 27.3).
               
![Cohorte_Japan](https://user-images.githubusercontent.com/33901438/78091969-af510080-73ce-11ea-91c9-c8981c271600.png)       

![Cohorte_SouthKorea](https://user-images.githubusercontent.com/33901438/78091974-b4ae4b00-73ce-11ea-9d2b-f27e84039b0a.png)
